### PR TITLE
[Issue: 53] Widget display data fixes

### LINKED ISSUE #53: Get a demo with widgets and plots working
Go beyond the basic simple / web3. See what happens.

### PR DESCRIPTION
**Pull request by parente**
Fixes #53

### CODE REVIEW

**Comment by dalogsdon** [comment]
Do you want to push the cell outputs?

**Comment by parente** [comment]
This isn't working yet at all. I'm just putting a placeholder here so it's easier to look at the code together. I don't have a solution for how to get the cells associated yet.

File: public/js/widget-manager.js [hunk 1]
```diff
@@ -45,16 +61,73 @@ define(['jupyter-js-widgets'], function(Widgets) {
...
+     * iopub.status
+     * iopub.clear_output
+     * iopub.output
+     * shell.reply
+     * input
+     *
+     * view: ipywidget view instance
+     */
+    WidgetManager.prototype.callbacks = function(view) {
+        // TODO: only registering one callback until https://github.com/ipython/ipywidgets/pull/353
```
Comment (parente) [inline public/js/widget-manager.js]: This needs to change once the bug is fixed in ipywidgets. But the callback API might change in the shim too.

Since we pin to a git sha for ipywidgets today, this "fix" will continue to work until we move on.

File: public/js/widget-manager.js [hunk 2]
```diff
@@ -45,16 +61,73 @@ define(['jupyter-js-widgets'], function(Widgets) {
...
+        // is fixed
+        var mgr = this;
+        var callbacks = {
+            iopub : {
+                output: function(msg) {
+                    console.debug(msg.msg_type, view);
+                    // TODO: it's probably not always parent
+                    mgr.msgHandler(msg, view.options.parent.options.outputAreaModel);
```
Comment (parente) [inline public/js/widget-manager.js]: Look up the ancestor chain until we find the view.options that has `outputAreaModel` or the parent is null or `options.root: true` (which should be the same as `parent = null`).

File: public/js/widget-manager.js [hunk 3]
```diff
@@ -34,10 +35,24 @@ define(['jupyter-js-widgets'], function(Widgets) {
     };
     WidgetManager.prototype = Object.create(Widgets.ManagerBase.prototype);
 
+    /*
+     * Called when a ipywidget is added to the DOM.
```
Comment (jhpedemonte) [inline public/js/widget-manager.js]: Are we going away from the "ipywidget" name? Maybe "Jupyter widget"?

File: public/js/widget-manager.js [hunk 4]
```diff
@@ -45,16 +60,83 @@ define(['jupyter-js-widgets'], function(Widgets) {
...
+        }
+
+        var callbacks = {};
+        if(options.outputAreaModel) {
+            var mgr = this;
+            // TODO: only registering one callback until https://github.com/ipython/ipywidgets/pull/353
+            // is fixed
+            callbacks.iopub = {
+                output: function(msg) {
+                    mgr.msgHandler(msg, view.options.parent.options.outputAreaModel);
```
Comment (jhpedemonte) [inline public/js/widget-manager.js]: This should be `options.outputAreaModel`, right? After `while` loop above?

Comment (parente) [inline public/js/widget-manager.js]: Duh. Yes.

File: public/js/widget-manager.js (hunk 3 above)
Comment (parente) [inline public/js/widget-manager.js]: Yes. That's true. The JS side is jupyter widget. The backend side is still an ipywidget (for now).

**Comment by jhpedemonte** [comment]
Looks good. Will merge soon.
