### PR TITLE
[issue: 49] Send exceptions, stderr to console

### LINKED ISSUE #49: Hide stderr / exception tracebacks in dashboard view
Port of the styling added to `jupyter-incubator/dashboards` and `jupyter-incubator/dashboards_bundlers` recently.

### PR DESCRIPTION
**Pull request by parente**
Fixes #49

### CODE REVIEW

File: public/js/dashboard.js [hunk 1]
```diff
@@ -64,6 +64,7 @@ requirejs([
     function _consumeMessage(msg, outputArea) {
         var output = {};
         var content = msg.content;
+        outer:
```
Comment (jhpedemonte) [inline public/js/dashboard.js]: Is this a GOTO? I would prefer a better way to handle this, if possible.

Comment (parente) [inline public/js/dashboard.js]: Me too. Can either return, or rewrite the whole thing without case statements.

**Comment by parente** [comment]
Added one last fix where stderr was still getting dumped into the page. Should be ready to :shipit: .

File: public/js/dashboard.js [hunk 2]
```diff
@@ -61,50 +61,61 @@ requirejs([
         $container.removeClass('invisible');
     }
 
+    // delegates for kernel message handling, keyed by message type
+    // all functions receive the entire response message and a reference to an
+    // outputArea model associated with the code / widget that made the initial
+    // request associated with the received response
```
Comment (jhpedemonte) [inline public/js/dashboard.js]: Nit: This seems like multiple sentences. Add caps and punctuation to make it more readable.

File: public/js/dashboard.js [hunk 3]
```diff
@@ -61,50 +61,61 @@ requirejs([
...
+            output.outputType = OutputType.ExecuteResult;
+            output.data = msg.content.data;
+            output.metadata = msg.content.metadata;
+            output.execution_count = msg.content.execution_count;
+            outputArea.add(output);
+        },
+        error: function(msg, outputArea) {
+            // show tracebacks in the console, not on the page
+            var traceback = msg.content.traceback.join('\n');
+            console.error(msg.content.ename, msg.content.evalue, traceback);
```
Comment (jhpedemonte) [inline public/js/dashboard.js]: In the future, will we want to show something in the page, so user knows that a given section of dashboard failed? Otherwise, user may not know to look in console for error details. Maybe a simple red icon?

**Comment by jhpedemonte** [comment]
Didn't test, but looks good. Ready to merge after comment update.

File: public/js/dashboard.js (hunk 3 above)
Comment (parente) [inline public/js/dashboard.js]: Probably in the case of error specifically. stderr dribbles warnings all over the place and really isn't a good indicator of a true problem.

I can open that as a follow on enhancement. Some kind of error doohicky in the nav bar. For the moment, let's just replicate what we had using Thebe: sending errors to the console.

Comment (parente) [inline public/js/dashboard.js]: Opened as #59
